title: Artificial Intelligence
description: >-
  Artificial Intelligence has taken over whole world, whole world is moving
  towards latest updated technology. Now a days robots are taking place of
  humans, 50% of the jobs got automated due to AI technologies. therefore the
  demand for AI is increasing.
template:
  repo: artificial-intelligence-template
  name: artificial-intelligence
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
